### PR TITLE
Fix user account switching issue

### LINKED ISSUE #136: Pulumi feature fails to install with bash completion
Using a simple configuration, Pulumi fails to install with its default parameters:

```
{
    "name": "devcontainer",
    "image": "mcr.microsoft.com/devcontainers/base:bullseye",
    "features": {
        "ghcr.io/devcontainers-contrib/features/pulumi:1": {}
    }
}
```

From the container log, the relevant part seems to be the "Permission denied" errors for creating a symbolic link and for bash completion.

```
#0 11.20 === Pulumi is now installed! 🍹 ===
#0 11.20 + Please restart your shell or add /home/vscode/.pulumi/bin to your $PATH
#0 11.20 + Get started with Pulumi: https://www.pulumi.com/docs/quickstart
#0 11.20 ln: failed to create symbolic link '/usr/local/bin/pulumi': Permission denied
#0 11.21 /bin/bash: line 7: /etc/bash_completion.d/pulumi: Permission denied
#0 11.21 ERROR: Feature "Pulumi" (ghcr.io/devcontainers-contrib/features/pulumi) failed to install! Look at the documentation at https://github.com/devcontainers-contrib/features/tree/main/src/pulumi for help troubleshooting this error.
```

Setting `"BASHCOMPLETION":false' like so:
```
"ghcr.io/devcontainers-contrib/features/pulumi:1": {"BASHCOMPLETION":false}
```
allows the container to be successfully built.

### PR DESCRIPTION
**Pull request by jcbhmr**
Fixes #136

In the future it might also be good to add more tests?

### CODE REVIEW

File: src/pulumi/install.sh [hunk 1]
```diff
@@ -51,13 +51,15 @@ sudo -iu "$_REMOTE_USER" <<EOF
...
+    if ! [ -x "\$(command -v pulumi)" ]; then
+        # We need sudo here since we are running under \$_REMOTE_USER
+        sudo ln -s \$HOME/.pulumi/bin/pulumi /usr/local/bin/pulumi
     fi
 
     # finally we are adding bash completion. zsh support will be added soon
     if [[ "${BASH_COMPLETION}" = "true" ]] ; then
-        pulumi gen-completion bash > /etc/bash_completion.d/pulumi
+        # We need sudo here since we are running under \$_REMOTE_USER
+        sudo pulumi gen-completion bash > /etc/bash_completion.d/pulumi
```
Comment (fred-asimov) [inline src/pulumi/install.sh:62]: Unfortunately, this `sudo` isn't enough, because it only runs the pulumi command as root. The redirection is done in userland, so it still fails.

Comment (jcbhmr) [reply src/pulumi/install.sh:62]: Drat! I don't even know how to accurately test this on my own local machine! Do you have any tips/advice so I can actually ensure/test/verify that these fixes that I'm trying work without publishing them to the ghcr.io registry?

Comment (fred-asimov) [inline src/pulumi/install.sh:62]:
```suggestion
pulumi gen-completion bash | sudo tee /etc/bash_completion.d/pulumi
```

**Comment by jcbhmr** [comment]
So it looks like the issue is still open.

To fix the permission error, there is more needed, as @fred-asimov says (and he is correct from a cursory SO glance)

Someone else [suggested using `dd` to ✨ magically make it work](https://stackoverflow.com/questions/82256/how-do-i-use-sudo-to-redirect-output-to-a-location-i-dont-have-permission-to-wr)

image

[Also it looks like @fred-asimov suggests:](https://github.com/devcontainers-contrib/features/pull/137#discussion_r1035250863)

```diff
-sudo pulumi gen-completion bash > /etc/bash_completion.d/pulumi
+pulumi gen-completion bash | sudo tee /etc/bash_completion.d/pulumi
```

@danielbraun89 We/I need some more testing things to somehow actually try to catch these things. I'm making lots of mistakes! And mistakes are good when you have someone/some-robot to catch them, but I personally have no wish to push out non-functional code to people like @fred-asimov and @DaneWeber like I have done so far 😢. It's not very good.

Any suggestions anyone to help catch these earlier? Something in the `test/` folder maybe? More robust shell testing?

File: src/pulumi/install.sh (hunk 1 above)
Comment (fred-asimov) [reply src/pulumi/install.sh:62]: Yeah, that's a tough one. :/ Maybe something that spins up a container and runs the feature installer inside of it, would be similar to the real world scenario. I can give it some thought. :)

**Comment by fred-asimov** [comment]
> Any suggestions anyone to help catch these earlier? Something in the `test/` folder maybe? More robust shell testing?

First off, don't sweat it, it's a hard-to-predict bug that's really difficult to test!

I think at a higher level, in terms of devcontainer fixtures, it would make sense to have an integration/smoke test (that runs on everything, not something that every feature has to maintain separately), which actually creates a devcontainer with the feature. I'm not entirely sure how to do that programmatically.

It might be sufficient to have a test that pulls a basic docker image, or even the base devcontainer image, and then checks out the feature and runs `install.sh` inside of it. That probably would have been enough to catch this. I can give that a try soon, and see if it's as easy as I'm claiming. 😆

**Comment by DaneWeber** [comment]
> Any suggestions anyone to help catch these earlier? Something in the `test/` folder maybe? More robust shell testing?

I haven't looked into what's required, but I'd think supporting the following would Pretty Darn Good:
* Run the tests as a non-root user (the `REMOTE_USER` such as `vscode`)
* Provide a `.devcontainer.json` for each test suite. In particular, I'd like to run tests with defaults and another with specified values.
* Besides looking for the check commands to run without error, it would be cool to run regex patterns against the output for higher-fidelity but resilient tests.

Some of these installs download a _ton_ of data, so it might be important to cache the downloads somehow.
